### ISSUE TITLE
Add some examples

### ISSUE THREAD

**Issue by remizovm** [remizovm/geonames#3]
Maybe I need to add some examples in case that tests are not enough.

**Comment by sundarv85** [comment]
This will be really valuable. We are looking for getting IATA codes for City names. Just wondering, if this is possible.

**Comment by remizovm** [comment]
@sundarv85 , if I understood you correctly, then IATA codes are stored in the alternate names list of every feature (if any). Will it be enough for you if i'll show how to get feature by it's IATA code?
